# permissions for end users to edit managedkafkas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: managedkafka-editor-role
rules:
- apiGroups:
  - streaming.my.domain
  resources:
  - managedkafkas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - streaming.my.domain
  resources:
  - managedkafkas/status
  verbs:
  - get
