name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.29
          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true

          # Optional: golangci-lint command line arguments.
          # args: --issues-exit-code=0

    - name: Check if formatted
      run: make formatCheck
    - name: Check passes golang standards
      run: make verify
    - name: Build
      run: make binary
    - name: Test
      run: make test

